### PR TITLE
Use default system dirs

### PR DESCRIPTION
**Pull request by kvaps**
This PR sets default system directories:

- `~/.cache/i3lock-multimonitor` - for caching
- `/usr/share/i3lock-multimonitor` - for the default resources

It will allow to prepare aur package with i3lock-multimonitor, and place it to
- `/usr/bin/i3lock-multimonitor`

### CODE REVIEW

**Comment by ShikherVerma** [comment]
@kvaps Thanks for the contribution. Changes look good. I'm not actively maintaining this project so I have added you as contributor. Please feel free to merge this and anything else you see fit.

**Comment by kvaps** [comment]
Got it! OK, I'll prepare an aur package

**Comment by kvaps** [comment]
AUR package prepared https://aur.archlinux.org/packages/i3lock-multimonitor/ 🎉🎉

**Comment by ShikherVerma** [comment]
Awesome!

**Comment by Strongleong** [comment]
2 and a half years late to comment here, but still...
You should use `$XDG_CACHE_HOME` env variable instead of hardcoding path to the cache dir.
I will make pull request to fix this

**Comment by ShikherVerma** [comment]
Thanks for the contribution.

**Pull request merged**
